files:
  - source: src/Mewdeko/data/strings/commands/commands.en-US.yml
    translation: src/Mewdeko/data/strings/commands/commands.%locale%.yml
  - source: /src/Mewdeko/data/strings/responses/responses.en-US.json
    translation: /src/Mewdeko/data/strings/responses/responses.%locale%.json
